#ifndef VSOMEIP_EXAMPLES_SAMPLE_IDS_HPP
#define VSOMEIP_EXAMPLES_SAMPLE_IDS_HPP

 

#define SAMPLE_SERVICE_ID       1667
#define SAMPLE_INSTANCE_ID      1405
#define SAMPLE_METHOD_ID        0

 


#define SAMPLE_EVENT_ID         65468
#define SAMPLE_GET_METHOD_ID    0x0001
#define SAMPLE_SET_METHOD_ID    0x0002

 

#define SAMPLE_EVENTGROUP_ID    1

 

#define OTHER_SAMPLE_SERVICE_ID 0x0248
#define OTHER_SAMPLE_INSTANCE_ID 0x5422
#define OTHER_SAMPLE_METHOD_ID  0x1421

 

#endif // VSOMEIP_EXAMPLES_SAMPLE_IDS_HPP
